// Auth action types

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const PERSIST_USER = "PERSIST_USER";

// Workout actions
export const TOGGLE_WORKOUT_MODAL = "TOGGLE_WORKOUT_MODAL";

export const TOGGLE_ADD_WORKOUT_FORM = "TOGGLE_ADD_WORKOUT_FORM";

export const ADD_WORKOUT_START = "ADD_WORKOUT_START";
export const ADD_WORKOUT_SUCCESS = "ADD_WORKOUT_SUCCESS";
export const ADD_WORKOUT_FAILURE = "ADD_WORKOUT_FAILURE";

export const FETCH_WORKOUTS_START = "FETCH_WORKOUTS_START";
export const FETCH_WORKOUTS_SUCCESS = "FETCH_WORKOUTS_SUCCESS";
export const FETCH_WORKOUTS_FAILURE = "FETCH_WORKOUTS_FAILURE";

export const UPDATE_WORKOUT_START = "UPDATE_WORKOUT_START";
export const UPDATE_WORKOUT_SUCCESS = "UPDATE_WORKOUT_SUCCESS";
export const UPDATE_WORKOUT_FAILURE = "UPDATE_WORKOUT_FAILURE";

export const DELETE_WORKOUT_START = "DELETE_WORKOUT_START";
export const DELETE_WORKOUT_SUCCESS = "DELETE_WORKOUT_SUCCESS";
export const DELETE_WORKOUT_FAILURE = "DELETE_WORKOUT_FAILURE";

// Exercise actions
export const ADD_EXERCISE_START = "ADD_EXERCISE_START";
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_FAILURE = "ADD_EXERCISE_FAILURE";

export const FETCH_EXERCISES_START = "FETCH_EXERCISES_START";
export const FETCH_EXERCISES_SUCCESS = "FETCH_EXERCISES_SUCCESS";
export const FETCH_EXERCISES_FAILURE = "FETCH_EXERCISES_FAILURE";

export const UPDATE_EXERCISES_START = "UPDATE_EXERCISES_START";
export const UPDATE_EXERCISES_SUCCESS = "UPDATE_EXERCISES_SUCCESS";
export const UPDATE_EXERCISES_FAILURE = "UPDATE_EXERCISES_FAILURE";

export const DELETE_EXERCISES_START = "DELETE_EXERCISES_START";
export const DELETE_EXERCISES_SUCCESS = "DELETE_EXERCISES_SUCCESS";
export const DELETE_EXERCISES_FAILURE = "DELETE_EXERCISES_FAILURE";
